hobbit/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

import apps.accounts.views
import apps.onboarding.views
import apps.homepage.views
import apps.habits.views
from apps.accounts.forms import HobbitAuthenticationForm, HobbitPasswordResetNotStupidForm

from django.contrib import admin
admin.autodiscover()

def secured_url(path, view, *args, **kwargs):
    return url(path, login_required(view), *args, **kwargs)

urlpatterns = patterns('',
    # url(r'^$', TemplateView.as_view(template_name='homepage/home.html'), name='homepage'),
    url(r'^$', apps.homepage.views.HomepageView.as_view(), name='homepage'),
    url(r'^logout/$', apps.accounts.views.LogoutView.as_view(), name='logout'),
    url(r'^password-change/$', apps.accounts.views.password_change, name='password_change'),
    url(r'^password-change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
    secured_url(r'^accounts/settings', apps.accounts.views.SettingsView.as_view(), name='account_settings'),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'apps.accounts.views.password_reset_confirm',
        {'post_reset_redirect': '/'},
        name='password_reset_confirm'),
    url(r'^email-confirm/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'apps.onboarding.views.confirm_email_address',
        ),
    url(r'^_;', include('apps.autologin.urls')),

    url(r'^add-habit/(?P<step>.+)/$', apps.onboarding.views.add_habit_wizard, name='add_habit_step'),
    url(r'^add-habit/$', apps.onboarding.views.add_habit_wizard, name='add_habit'),

    secured_url(r'^habit-performance.json$', apps.habits.views.HabitPerformanceView.as_view(), name='habit_performance'),
    secured_url(r'^habit/(?P<pk>\d+)/$', apps.habits.views.HabitDetailView.as_view(), name='habit'),
    secured_url(r'^habit/(?P<pk>\d+)/edit$', apps.habits.views.HabitEditView.as_view(), name='habit_edit'),
    secured_url(r'^habit/(?P<pk>\d+)/archive$', apps.habits.views.HabitArchiveView.as_view(), name='habit_archive'),
    secured_url(r'^habit/(?P<pk>\d+)/record/$', apps.habits.views.habit_record_view, name='habit_record'),
    secured_url(r'^habit/(?P<pk>\d+)/recorded/$', apps.habits.views.HabitEncouragementView.as_view(), name='habit_encouragement'),
    url(r'^styletile$', TemplateView.as_view(template_name='styles/tile.html'), name='styletile'),

    url(r'^hobbit/$', TemplateView.as_view(template_name='hobbit.html'), name='hobbit'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

) + patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'accounts/login.html', 'authentication_form': HobbitAuthenticationForm}, name='login'),
    url(r'^accounts/forgot/$', 'password_reset', {'password_reset_form': HobbitPasswordResetNotStupidForm, 'email_template_name': 'emails/accounts/password_reset.html'}, name='account_forgotten'),
    url(r'^accounts/forgot/done/$', 'password_reset_done'),
)

from apps.monitoring import *

apps/habits/models.py
from __future__ import division, unicode_literals

from collections import namedtuple
import datetime

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.humanize.templatetags.humanize import ordinal

from .signals import habit_archived, habit_created, habit_data_recorded

RESOLUTIONS = (
    ('day',        _('day')),
    ('weekday',    _('day on weekdays')),
    ('weekendday', _('day on weekends')),
    ('week',       _('week')),
    ('month',      _('month')),
)

RESOLUTIONS_NO_MONTH = (
    ('day',        _('day')),
    ('weekday',    _('day on weekdays')),
    ('weekendday', _('day on weekends')),
    ('week',       _('week')),
)

def _validate_non_negative(val):
    if val < 0:
        raise ValidationError(u'%s is not greater than or equal to zero' % val)

def _validate_datetime_is_hour(val):
    if val.minute != 0 or val.second != 0 or val.microsecond != 0:
        raise ValidationError(u'%s must have zero-valued minutes, seconds, and microseconds when representing an hour' % val)

TimePeriod_ = namedtuple('TimePeriod', 'resolution index date')

class TimePeriod(TimePeriod_):

    @classmethod
    def from_index(cls, start, resolution, index):
        """Construct a TimePeriod from a start date, a resolution, and a given index"""
        if resolution == 'day':
            date = start + datetime.timedelta(days=index)

        # In order to convert an index to a date for weekdays and weekenddays,
        # we need to work out how many weeks and days to jump forward in time
        # from the start date. This turns out to be quite an interesting
        # problem, and I found it easiest to picture the solution in a table,
        # as shown below.
        #
        # The trick is to use modular arithmetic to count weeks and days from
        # the start of the week in which the start date falls. For start dates
        # that don't fall on a Monday (or a Saturday for weekenddays), we must
        # shift the day and week offsets left by a number of places equivalent
        # to the integer week number of the start date.
        #
        # For example, for weekdays, starting on a Tuesday, the offset is 1,
        # so:
        #
        #   M T W T F S S M T W T F S S M ...
        #   index:
        #     0 1 2 3     4 5 6 7 8     9 ...
        #   week_offset:
        #   0 0 0 0 0     1 1 1 1 1     2 ...
        #   day_offset:
        #   0 1 2 3 4     0 1 2 3 4     0 ...
        #
        # A similar diagram for weekenddays (starting on a Sunday):
        #
        #   S S M T W T F S S M ...
        #   index:
        #     0           1 2   ...
        #   week_offset:
        #   0 0           1 1   ...
        #   day_offset:
        #   0 1           0 1   ...
        #
        elif resolution == 'weekendday':
            if start.weekday() < 5:
                # Skip forward to Saturday
                date = start + datetime.timedelta(days=5 - start.weekday())
                offset = 0
            else:
                date = start - datetime.timedelta(days=start.weekday() - 5)
                offset = start.weekday() - 5

            week_offset = (index + offset) // 2
            day_offset = (index + offset) % 2

            date += datetime.timedelta(days=7 * week_offset + day_offset)

        elif resolution == 'weekday':
            if start.weekday() >= 5:
                # Skip forward to Monday
                date = start + datetime.timedelta(days=7 - start.weekday())
                offset = 0
            else:
                date = start - datetime.timedelta(days=start.weekday())
                offset = start.weekday()

            week_offset = (index + offset) // 5
            day_offset = (index + offset) % 5

            date += datetime.timedelta(days=7 * week_offset + day_offset)

        elif resolution == 'week':
            start_week = start - datetime.timedelta(days=start.weekday())
            date = start_week + datetime.timedelta(days=index * 7)

        elif resolution == 'month':
            year = start.year + index // 12
            month = start.month + index % 12
            date = datetime.date(year, month, 1)

        else:
            raise RuntimeError("Unhandled resolution: %s" % resolution)

        return cls(resolution, index, date)

    @classmethod
    def from_date(cls, start, resolution, date):
        """Construct a TimePeriod from a start date, a resolution, and a given date"""
        tp_index = None
        tp_date = None

        if resolution == 'day':
            tp_index = (date - start).days
            tp_date = date

        elif resolution == 'week':
            start_week = start - datetime.timedelta(days=start.weekday())
            date_week = date - datetime.timedelta(days=date.weekday())

            tp_index = (date_week - start_week).days // 7
            tp_date = date_week

        elif resolution in ['weekday', 'weekendday']:
            start_week = start - datetime.timedelta(days=start.weekday())
            date_week = date - datetime.timedelta(days=date.weekday())

            num_days = (date - start).days + 1
            num_weekend_days = _num_weekend_days_between(start, date)

            if resolution == 'weekday':
                tp_index = num_days - num_weekend_days - 1
                if tp_index < 0:
                    raise ValueError("No weekdays have passed since start")
                if date.weekday() < 5:
                    tp_date = date
                else:
                    # Skip back to Friday
                    tp_date = date - datetime.timedelta(days=date.weekday() - 4)
            else:
                tp_index = num_weekend_days - 1
                if tp_index < 0:
                    raise ValueError("No weekends have passed since start")
                if date.weekday() >= 5:
                    tp_date = date
                else:
                    # Skip back to Sunday
                    tp_date = date - datetime.timedelta(days=date.weekday() + 1)

        elif resolution == 'month':
            start_month = start.replace(day=1)
            date_month = date.replace(day=1)

            year_diff = date_month.year - start_month.year
            month_diff = date_month.month - start_month.month

            tp_index = year_diff * 12 + month_diff
            tp_date = date_month

        else:
            raise RuntimeError("Unhandled resolution: %s" % resolution)

        return cls(resolution, tp_index, tp_date)

    def friendly_date(self):
        return self._friendly_date_relative_to(datetime.date.today())

    def _friendly_date_relative_to(self, relative_to):
        if self.resolution == "week":
            return self._friendly_weekly_date(relative_to)
        else:
            return self._friendly_daily_date(relative_to)

    def _friendly_daily_date(self, relative_to):
        delta_days = (relative_to - self.date).days
        if delta_days == 0:
            return _("Today")
        elif delta_days == 1:
            return _("Yesterday")
        elif delta_days < 7:
            # Full day name
            return self.date.strftime("%A")
        else:
            # "March 1st"
            return "%s %s" % (self.date.strftime("%B"), ordinal(self.date.day))

    def _friendly_weekly_date(self, relative_to):
        return "Week of %s %s" % (self.date.strftime("%B"), ordinal(self.date.day))


class Habit(models.Model):
    """
    A habit and its associated data.
    """

    user = models.ForeignKey('accounts.User', related_name='habits')
    resolution = models.CharField(
        max_length=10,
        choices=RESOLUTIONS,
        default='day',
    )
    start = models.DateField()
    target_value = models.PositiveIntegerField(default=1)
    description = models.TextField()
    archived = models.BooleanField(default=False)

    reminder = models.TextField(
        null=True,
        blank=True,
    )
    reminder_days = models.IntegerField(
        validators=[_validate_non_negative],
        default=0,
    )
    reminder_hour = models.IntegerField(
        validators=[_validate_non_negative],
        default=None,
        null=True,
        blank=True
    )
    reminder_last_sent = models.DateTimeField(
        validators=[_validate_datetime_is_hour],
        null=True,
        blank=True
    )
    send_data_collection_emails = models.BooleanField(default=True)

    class Meta:
        # HACK: Use ID as proxy for creation order
        ordering = ['archived', '-id']

    @classmethod
    def scheduled_for_reminder(cls, weekday, hour):
        """
        Get all habits scheduled for a reminder on the given ``weekday`` and
        ``hour``. ``weekday`` should be an integer weekday
        (Monday=0...Sunday=6).
        """
        return cls.objects.raw("""
            SELECT * FROM habits_habit
            WHERE (reminder_days & %s) != 0
            AND reminder_hour = %s
        """, [1 << weekday, hour])

    def save(self, *args, **kwargs):
        # ensure that model field custom validators are always run before saving
        self.full_clean()
        return super(Habit, self).save(*args, **kwargs)

    def get_current_time_period(self):
        return self.get_time_period(datetime.date.today())

    def get_time_period(self, when, resolution=None):
        """
        Return the TimePeriod for the date given by ``when``, on the basis of
        the passed ``resolution`` (defaults to the Habit's ``resolution``).
        """
        if resolution is None:
            resolution = self.resolution

        return TimePeriod.from_date(self.start, resolution, when)

    def is_up_to_date(self):
        time_period = self.get_current_time_period()
        return self.get_buckets().filter(index=time_period.index).count() != 0

    def is_binary(self):
        """
        Returns true if this habit is a yes/no task (versus a how many times you

apps/habits/views.py
import json

from django.views.generic import View, DetailView, FormView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.views.decorators.cache import never_cache
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _
from django import forms

from apps.habits.models import Habit, habit_archived
from apps.habits.forms import HabitForm
from apps.encouragements import get_encouragement
from lib.metrics import statsd

class HabitDetailView(DetailView):
    model = Habit

    def get_queryset(self):
        return self.request.user.habits.all()


class HabitEditView(UpdateView):
    model = Habit
    form_class = HabitForm
    template_name_suffix = '_edit_form'

    def get_success_url(self):
        return reverse('homepage')


class HabitArchiveView(SingleObjectMixin, View):
    model = Habit

    def get_queryset(self):
        return self.request.user.habits.all()

    def get_success_url(self):
        return self.request.POST.get("next",
            self.request.META.get('HTTP_REFERER', reverse('habit', kwargs={'pk': self.get_object().id}))
        )

    @never_cache
    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.archived = request.POST.get("archive") == "1"
        habit_archived.send(obj)
        obj.save()
        return HttpResponseRedirect(self.get_success_url())

@never_cache
def habit_record_view(request, pk):
    habit = get_object_or_404(Habit, pk=pk, user=request.user)

    time_periods = habit.get_recent_unentered_time_periods()

    if len(time_periods) == 0:
        return HttpResponseRedirect(reverse('homepage'))

    _forms = []

    for period in time_periods:
        # To make the label for the input dynamic we need to create a new class
        # each time. This might be better done as a Widget instead...?
        class HabitForm(forms.Form):
            date = forms.DateField(required=True, widget=forms.HiddenInput)
            value = forms.IntegerField(min_value=0, label=period.friendly_date())

        if request.method == 'POST': # If the form has been submitted...
            data = request.POST
            initial = None
        else:
            data = None
            initial = {'date': period.date}

        _forms.append(HabitForm(data=data, initial=initial, prefix=str(period.index)))

    if request.method == 'POST': # If the form has been submitted...
        if all(map(lambda f: f.is_valid(), _forms)):
            for form in _forms:
                time_period = habit.get_time_period(form.cleaned_data['date'])
                habit.record(time_period, form.cleaned_data['value'])
            return HttpResponseRedirect(reverse('habit_encouragement', args=[habit.id]))

    return render(request, 'habits/habit_record_form.html', {
        'forms': _forms,
        'habit': habit,
    })


class HabitEncouragementView(DetailView):
    model = Habit
    template_name = "habits/habit_encouragement.html"

    def get_context_data(self, **kwargs):
       ctx = super(HabitEncouragementView, self).get_context_data(**kwargs)
       ctx['encouragement'] = get_encouragement(self.get_object())
       return ctx


RECENT_BUCKETS = 20

class HabitPerformanceView(View):

    def get(self, request, *args, **kwargs):
        result = {'habits': []}

        for habit in request.user.habits.filter(archived=False):
            current = habit.get_current_time_period()
            recent_buckets = [None] * RECENT_BUCKETS

            for bucket in habit.get_buckets().filter(index__gt=current.index - RECENT_BUCKETS):
                recent_buckets[bucket.index - current.index - 1] = bucket.value

            result['habits'].append({'description': habit.description,
                                     'resolution': habit.resolution,
                                     'target_value': habit.target_value,
                                     'recent_buckets': recent_buckets})

        return HttpResponse(json.dumps(result), content_type='application/json')

templates/habits/habit_edit_form.html
{% extends "base.html" %}
{% block title %}Edit habit{% endblock %}
{% block main-class %}copy{% endblock %}
{% block body-class %}centred-wtf add-trigger{% endblock %}

{% block body %}
  <div class="edit-habit-header">
    <h1>Edit Action</h1>
    <form method="POST" action="{% url 'habit_archive' pk=habit.pk %}" class="archive">
      {% csrf_token %}
      {% if habit.archived %}
      	<button type="submit" class="progress meh">Revive</button>
	<input name="archive" value="0" type="hidden">
      {% else %}
        <button type="submit" class="progress meh">Put to rest</button>
        <input name="archive" value="1" type="hidden">
      {% endif %}
    </form>
  </div>

  <form id="edit-habit-form" action="" method="POST" class="edit-habit">
    {% csrf_token %}

    {% if form.errors %}
        <p class="alert">
          <strong>
            {% if form.errors.description %}
              "I want to" {{ form.errors.description.as_text }} <br>
            {% endif %}
            {% if form.errors.target_value %}
              "times" {{ form.errors.target_value.as_text }} <br>
            {% endif %}
            {% if form.errors.resolution %}
              "per" {{ form.errors.resolution.as_text }} <br>
            {% endif %}
          </strong>
        </p>
    {% endif %}

    <p>
      <label for="id_description">I want to {{ form.description }}</label>,<br>
      <label for="id_target_value">{{ form.target_value }} times</label>
      <label for="id_resolution">per {{ form.resolution }}</label>
      <br>
    </p>

    <div class='reminder'>
      <fieldset class='trigger-text'>
        <h2>My trigger reminder:</h2>
        <p>
         <label for='id_reminder-trigger'>When I</label>
         {{ form.reminder }},
         then I <q>{{ habit.description }}</q>.
        </p>
      </fieldset>
      
      <fieldset class='trigger-time'>
        <legend>Send reminder</legend>
        <h2>When should we send this?</h2>
        <div class='columnar'>
          <span>Every</span>
          {{ form.reminder_days }}
        </div>
        <p>
          <label for="id_reminder-hour">at</label> {{ form.reminder_hour }}
          <!-- GMT or GTFO -->
        </p>
      </fieldset>
    </div>

    <div class="form-continue">
      <button type='submit' class="progress">Save</button>
    </div>
  </form>
{% endblock %}

templates/habits/habit_encouragement.html
{% extends "base.html" %}

{% block title %}Good Job!{% endblock %}

{% block body %}
  <h2>Well done!</h1>
  <p id='encouragement'>{{ encouragement }}</p>
  
  <form method='GET' action='{% url "homepage" %}'>
    <button type='submit' class='progress'>Yo.</button>
  </form>
{% endblock %}

templates/habits/habit_record_form.html
{% extends "base.html" %}
{% block title %}How's it going?{% endblock %}
{% block body %}
  {% if habit.is_binary %}
    <h1>Did you do your habit: <q>{{ habit.description }}?</q></h1>
  {% else %}
    <h1>How many times did you <q>{{ habit.description }}?</q></h1>
  {% endif %}

  <form id="data-entry" method="POST" action="">
    {% csrf_token %}
    <ul>
      {% for form in forms %}
        <li>
          {% for field in form %}
            {% if field.is_hidden %}
              {{ field }}
            {% else %}
              {{ field.errors }}
              {{ field.label_tag }}
              {% if habit.is_binary %}
                {# the hidden input means that unchecked still submits #}
                <input type='hidden' name='{{ field.html_name }}' 
                       id='{{ field.id_for_label }}' value='0'>
                <input type='checkbox' name='{{ field.html_name }}' 
                       id='{{ field.id_for_label }}' value='1'>
              {% else %}
                {{ field }}
              {% endif %}
            {% endif %}
          {% endfor %}
        </li>
      {% endfor %}
    </ul>
    <button type='submit' class='progress'>Done</button>
  </form>
{% endblock %}

{% block javascript-enhance %}
  (function( $ ){
      $.fn.make_into_switch = function() {
          var create_switch_html = function (el) {
              var $button = $('<button/>').text('Y').bind(
                      'click', function(ev) {
                          change_switch_state(ev, el);
                          return false;
                      }
                  );
              
              if ( $(el).attr('checked') == 'checked' ) {
                  $button.addClass('on');
              }
              
              $(el).before( $button ).addClass('enhanced');
          }
          
          var change_switch_state = function (ev, el) {
              var $button = $('button', $(ev.target).parent() );
              if ( $(el).attr('checked') ) {
                  $(el).attr('checked', false);
                  $button.removeClass('on');
              }
              else {
                  $(el).attr('checked', true);
                  $button.addClass('on');
              }
          };
          
          this.each( function() {
              create_switch_html( $(this) );
          })
          
          this.bind('change', function(ev) {
              change_switch_state(ev, this);
          });
      };
  })( jQuery );

  $(function() {
      $('input[type=checkbox]').make_into_switch();
  });
{% endblock %}